[build.environment]
  command = "npm run build"
  publish = "out"
  NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyBrYO3H10JRMue_JmXWUG1ZailSY3EJJTU"
  NEXT_PUBLIC_FIREBASE_APP_ID = "1:1012357491167:web:926c4584af6bb62b79fc6a"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "afalgun-auth.firebaseapp.com"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "afalgun-auth"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "afalgun-auth.appspot.com"
 
 
